<?php

// Load the Composer autoloader (may be symlinked in worktrees)
$loader = require __DIR__ . '/../vendor/autoload.php';

// The symlinked vendor/ carries the parent project's classmap (generated by composer
// dump-autoload in the parent). Classmap entries take precedence over PSR-4, so simply
// calling setPsr4() isn't enough — the parent's App\* classes would still load from the
// classmap. Strip all App\ entries from the classmap via reflection so PSR-4 wins, then
// point PSR-4 at this worktree's app/ directory. Safe no-op when not in a worktree.
$ref = new \ReflectionProperty($loader, 'classMap');
$ref->setAccessible(true);
$ref->setValue($loader, array_filter(
    $loader->getClassMap(),
    fn ($k) => !str_starts_with($k, 'App\\'),
    ARRAY_FILTER_USE_KEY
));
$loader->setPsr4('App\\', [realpath(__DIR__ . '/../app')]);

// Application::inferBasePath() falls back to the Composer ClassLoader's registered
// path, which follows the symlink and points to the parent project. Override it here
// so Laravel bootstraps from this worktree's root instead.
$worktreeRoot = realpath(__DIR__ . '/..');
$_ENV['APP_BASE_PATH'] = $worktreeRoot;
$_SERVER['APP_BASE_PATH'] = $worktreeRoot;
